### PR TITLE
Fix UB in Windows verifier EKU handling 

### LINKED ISSUE #126: TLS Runtime Issues for GitHub Artifacts built on Windows
Hello 😊 We have discovered a weird runtime TLS bug happening for artifacts built on the GitHub Windows runners. We have an example repository showcasing a simplified example here:

https://github.com/Thomas-Avery/test-rustls-platform-verifier

You can find the built artifact here:

https://github.com/Thomas-Avery/test-rustls-platform-verifier/actions/runs/10378079748

The error when running this artifact:

```
PS C:\Users\Colton\Desktop> .\test-rustls-platform-verifier.exe
[2024-08-22T17:19:28Z ERROR rustls_platform_verifier::verification::windows] failed to verify TLS certificate: invalid peer certificate: InvalidPurpose
Error: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("httpbin.org")), port: None, path: "/ip", query: None, fragment: None }, source: hyper_util::client::legacy::Error(Connect, Custom { kind: Other, error: Custom { kind: InvalidData, error: InvalidCertificate(InvalidPurpose) } }) }
```

error

### PR DESCRIPTION
**Pull request by complexspaces**
This PR implements two fixes in the Windows verifier to fix UB and future-UB:
- Properly `NULL`-terminate the EKU strings we pass in.
- Only pass in a thin pointer containing the string data to Windows, not the slice's fat pointer.

See the linked issue for a more detailed analysis if your curious why this was never problematic before.

Closes #126

### CODE REVIEW

**Comment by complexspaces** [comment]
@ctz I meant to open a PR against the [rel-0.1](https://github.com/rustls/rustls-platform-verifier/commits/rel-0.1/) branch with this backport since its UB/important bugfix but I mistakenly pushed this commit to the branch instead. I apologize for that. Please make sure it matches this for diligence as part of your review.

File: rustls-platform-verifier/src/verification/mod.rs [hunk 1]
```diff
@@ -74,14 +74,17 @@ fn invalid_certificate(reason: impl Into<String>) -> rustls::Error {
...
 
-#[cfg(any(windows, target_os = "android"))]
 /// List of EKUs that one or more of that *must* be in the end-entity certificate.
 ///
 /// Legacy server-gated crypto OIDs are assumed to no longer be in use.
 ///
 /// Currently supported:
 /// - id-kp-serverAuth
 // TODO: Chromium also allows for `OID_ANY_EKU` on Android.
+#[cfg(target_os = "windows")]
```
Comment (djc) [inline rustls-platform-verifier/src/verification/mod.rs:84]: If we have to declare these separately, maybe it makes more sense to move them into `android.rs` and `windows.rs`?

Also, maybe this is worth two lines of comments explaining the context here and/or linking to the issue?

**Review by djc — APPROVED** [review]

File: rustls-platform-verifier/src/verification/mod.rs [hunk 2]
```diff
@@ -74,14 +74,17 @@ fn invalid_certificate(reason: impl Into<String>) -> rustls::Error {
...
+const ALLOWED_EKUS: &[*mut u8] = &["1.3.6.1.5.5.7.3.1\0".as_ptr() as *mut u8];
```
Comment (ctz) [inline rustls-platform-verifier/src/verification/mod.rs:85]: 💭 raised #128 containing an idea on making this clearer.

Comment (ctz) [reply rustls-platform-verifier/src/verification/mod.rs:85]: 💭 also when our msrv allows it, we could use a `c""` string here

File: rustls-platform-verifier/src/verification/mod.rs (hunk 1 above)
Comment (complexspaces) [reply rustls-platform-verifier/src/verification/mod.rs:84]: I would prefer to keep these next to each other in the source since we still believe they should have the OIDs inside in sync for consistency between platforms.

**Review by ctz — APPROVED** [review]

File: rustls-platform-verifier/src/verification/mod.rs (hunk 2 above)
Comment (complexspaces) [reply rustls-platform-verifier/src/verification/mod.rs:85]: Yeah c string literals would be really nice here 😅

File: rustls-platform-verifier/src/verification/mod.rs (hunk 1 above)
Comment (complexspaces) [reply rustls-platform-verifier/src/verification/mod.rs:84]: I've updated this code to include a link to the issue and context around why the string handling looks the way it does.

File: rustls-platform-verifier/src/verification/mod.rs [hunk 3]
```diff
@@ -82,8 +82,11 @@ fn invalid_certificate(reason: impl Into<String>) -> rustls::Error {
 /// - id-kp-serverAuth
 // TODO: Chromium also allows for `OID_ANY_EKU` on Android.
 #[cfg(target_os = "windows")]
+// XXX: Windows requires that we NUL terminate EKU strings and we want to make sure that only the
```
Comment (djc) [inline rustls-platform-verifier/src/verification/mod.rs:85]: I think this sentence is missing a word. Otherwise LGTM!

Comment (complexspaces) [reply rustls-platform-verifier/src/verification/mod.rs:85]: Oops, good catch. I'll fix this when migrating to `windows_sys`.
